### ISSUE TITLE
Autocatcher Key error

### ISSUE THREAD

**Issue by Determineer** [Faizan2007/Poketwo-Autocatcher-Replit#3]
Whenever I run the program it displays a key error associated with my discord token, Idk what to do.

![pketwo aytocatcher error](https://user-images.githubusercontent.com/101373987/157789621-85e0981e-c456-41ec-b74e-b0a8c86dcbda.jpg)

**Comment by Faizan2007** [comment]
checkout https://github.com/rodofdiscord/persona. this project has been discontinued
